### PR TITLE
Fix api calls are authenticated by cookie when session type is refresh_token ref #164

### PR DESCRIPTION
**Pull request by tung2744**
ref #164

### CODE REVIEW

**Comment by louischan-oursky** [comment]
What problem did you encounter if cookie is also included when session type is token?

**Comment by tung2744** [comment]
@louischan-oursky As mentioned in #164, the problem is if I have a cookie session in authgear, and at the same time I am using refresh token session in js sdk.
After I called `logout` which revoked the refresh token session, when I call `fetchUserInfo` it will return the user info of my authgear cookie session, which I think is unexpected.

**Comment by louischan-oursky** [comment]
@carmenlau I added one commit to make credentials explicit in all places. And I have marked several API as credentials: omit. Can you have a look?

**Review by carmenlau — APPROVED** [review]
It looks good to me, please rebase.

Thanks @tung2744 @louischan-oursky

**Pull request merged**
