### PR TITLE
Align sdk with android sdk

### PR DESCRIPTION
**Pull request by roxk**
connect #17 #18 #19 #14

### CODE REVIEW

**Review by kiootic — COMMENTED** [review]
- We also have a SDK for web in `authgear-web` package, can you also help to update that as well?
- Linting failed, you can check the errors by running `npm run lint` locally.

**Comment by roxk** [comment]
@kiootic Most issues are for RN, which issue you have in mind that is missing in web? One I noticed is missing is
- [ ] fetch user info

**Comment by kiootic** [comment]
Most of the changes for RN should be applicable to web SDK as well, for example:
- signature of `configure` function
- default `prompt` parameter of `startAuthorization` (counterpart of RN's `authorize` function)

**Comment by roxk** [comment]
@kiootic Web needs to refresh access token? I thought web is always 1st party :o Got it.

**Comment by kiootic** [comment]
> Web needs to refresh access token? I thought web is always 1st party

Web app may be 1st party (e.g. authgear at `accounts.example.com`, traditional SSR web app at `example.com`), or 3rd party (e.g. authgear at `example-app.authgear.com`, SPA web app at `example.com`).

**Pull request merged**
