### PR TITLE
Expose fetch function from web and react-native container

### LINKED ISSUE #105: All "c" in the wechat name should be lower case
All "c" in the wechat name should be lower case

### PR DESCRIPTION
**Pull request by carmenlau**
refs #89

fix #105 

The fetch function is implemented in `BaseContainer` and the function was hidden during refactoring in #89.
Add back fetch in `WebContainer` and `ReactNativeContainer`

### CODE REVIEW

**Comment by louischan-oursky** [comment]
Would `onWechatLoginEnd` a better name for `weChatAuthCallback` of `ReactNativeContainer`?

**Comment by carmenlau** [comment]
> The authorizeEndpoint of WebContainer and ReactNativeContainer is exposed. It should be hidden.

I added this due to the discussion we had with Steven last time. If user want to do the direction themselves they can use this function to construct the url, this is for advance usage. But your questions remain me that, it is useful for web only? Maybe we should only add this to `WebContainer`. What do you think?

> Would onWechatLoginEnd a better name for weChatAuthCallback of ReactNativeContainer?

The original idea is `weChatAuthCallback` accepts  authorization code, so technically it is an auth callback that client delegate to the server. For me, both name are fine for me, since the wechat integration is not easy, user must read the guide.

**Comment by louischan-oursky** [comment]
> I added this due to the discussion we had with Steven last time. If user want to do the direction themselves they can use this function to construct the url, this is for advance usage. But your questions remain me that, it is useful for web only? Maybe we should only add this to WebContainer. What do you think?

Agree we should only make it available to WebContainer. Also the name of the function should start with a verb. Let's name it `makeAuthorizeURL`.

**Comment by louischan-oursky** [comment]
> The original idea is weChatAuthCallback accepts authorization code, so technically it is an auth callback that client delegate to the server. For me, both name are fine for me, since the wechat integration is not easy, user must read the guide.

What about lowercasing the C in `weChatAuthCallback` to make it `wechatAuthCallback`?

**Comment by carmenlau** [comment]
Updated!

**Pull request merged**
