### PR TITLE
Use origin in openid config to construct url

### PR DESCRIPTION
**Pull request by tung2744**
ref #248

### CODE REVIEW

**Comment by louischan-oursky** [comment]
IMG_7333

It seems that the URL class in React Native is only partially implemented https://github.com/facebook/react-native/issues/38966 https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Blob/URL.js#L186

**Comment by tung2744** [comment]
Oh I tested in android and it works.. Let me find another way to implement it then.

**Comment by louischan-oursky** [comment]
In core/container.ts, we use `import URL from "core-js-pure/features/url";` to import a working implementation of URL.

**Comment by tung2744** [comment]
@louischan-oursky Fixed, thanks!

**Pull request merged**
