### PR TITLE
Support x_state in latte

### PR DESCRIPTION
**Pull request by tung2744**

### CODE REVIEW

**Review by louischan-oursky — COMMENTED** [review]
- Add xState to ReauthenticateOptions
- Add xState to PromoteOptions

**Comment by tung2744** [comment]
@louischan-oursky So we will do the same in other sdks too? In other sdk the latte api share the same `AuthenticateOptions` class with the authgear api, so we need to separate them in this change.

**Comment by louischan-oursky** [comment]
Yes. Latte API can have its own option interfaces.

**Comment by tung2744** [comment]
Oh I found I replied in a wrong pr, why you know what I am talking about :shocked:

**Pull request merged**
