### PR TITLE
Update RN demo app UI

### PR DESCRIPTION
**Pull request by axolotl0212**
Align with other SDK, add text field for user to type in client ID and Authgear endpoint

#iOS screenshot

Screenshot 2020-11-16 at 2 43 50 AM

# Android screenshot

Screenshot_20201116-030312_reactNativeExample

### CODE REVIEW

**Comment by axolotl0212** [comment]
@louischan-oursky updated

**Comment by louischan-oursky** [comment]
https://github.com/authgear/authgear-sdk-js/pull/28 has been merged. Can you update the example to use session state instead of getting access token. Actually we should remove getting access token from the public API.

**Comment by axolotl0212** [comment]
> #28 has been merged. Can you update the example to use session state instead of getting access token. Actually we should remove getting access token from the public API.

pushed 1 more commit to use session state @louischan-oursky

**Comment by louischan-oursky** [comment]
Thanks!

**Pull request merged**
