### PR TITLE
Support biometric in Capacitor SDK

### PR DESCRIPTION
**Pull request by louischan-oursky**
ref #256

### CODE REVIEW

**Comment by tung2744** [comment]
@louischan-oursky Have you got this error when trying in simulator?
Screenshot 2024-01-17 at 1 35 58 PM

**Comment by louischan-oursky** [comment]
No. I tested on my own iPhone. Maybe simulator does not support secure enclave.

**Comment by louischan-oursky** [comment]
Let me take a look later when I have time.

**Comment by tung2744** [comment]
> Maybe simulator does not support secure enclave.

However, app2app can be run on simulator, which is also using secure enclave.

BTW, I also added a readme for capacitor example app in c23f468

**Comment by louischan-oursky** [comment]
I figure out the cause, but I could not find any reason on the web.

In the SecAccessControlCreateFlags, if we omit `.biometryAny` `.biometryCurrentSet` `.userPresence` , then we can enable biometric on Simulator. I think the simulator has some problem handling these flags.

**Pull request merged**
